In [2]:
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix
from keras.datasets import mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()

# Flatten the images
x_train = x_train.reshape((-1, 28*28)) / 255.0
x_test = x_test.reshape((-1, 28*28)) / 255.0

# Create and train the model
model = RandomForestClassifier(n_estimators=100)
model.fit(x_train, y_train)

# Predict
y_pred_classes = model.predict(x_test)

# Evaluation
print("\nClassification Report:")
print(classification_report(y_test, y_pred_classes))

conf_mat = confusion_matrix(y_test, y_pred_classes)
print("Confusion Matrix:")
print(conf_mat)



Classification Report:
              precision    recall  f1-score   support

           0       0.97      0.99      0.98       980
           1       0.99      0.99      0.99      1135
           2       0.96      0.97      0.96      1032
           3       0.95      0.96      0.96      1010
           4       0.98      0.98      0.98       982
           5       0.98      0.96      0.97       892
           6       0.98      0.98      0.98       958
           7       0.97      0.96      0.97      1028
           8       0.95      0.95      0.95       974
           9       0.96      0.95      0.96      1009

    accuracy                           0.97     10000
   macro avg       0.97      0.97      0.97     10000
weighted avg       0.97      0.97      0.97     10000

Confusion Matrix:
[[ 969    0    0    0    0    1    4    1    4    1]
 [   0 1122    3    3    0    2    3    0    2    0]
 [   5    0 1001    6    2    0    3    9    6    0]
 [   1    0   13  966    0    9    0    